name = "therealcool-site"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[routes]]
pattern = "therealcool.site/*"
zone_name = "therealcool.site"

[[routes]]
pattern = "www.therealcool.site/*"
zone_name = "therealcool.site"
